# Generated by Django 4.2.2 on 2023-07-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='place',
        ),
    ]
