# Generated by Django 4.2.2 on 2023-07-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_deliverytime_place_delivery_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='delivery_times',
        ),
    ]
